services:
  music-api:
    build: .
    container_name: music-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./songs:/app/songs
    command: uvicorn main:app --host 0.0.0.0 --port 8000
