server {
  listen 80;
  server_name rikkiee-music.duckdns.org;
  return 301 https://$server_name$request_uri;
}

server {
  listen 443 ssl;
  server_name rikkiee-music.duckdns.org;

  ssl_certificate /etc/letsencrypt/live/rikkiee-music.duckdns.org/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/rikkiee-music.duckdns.org/privkey.pem;

  location / {
    proxy_pass http://localhost:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
